apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: anotherclass-221
  name: api-tester-1
  labels:
    part-of: k8s-anotherclass
    component: backend-server
    name: api-tester
    instance: api-tester
    version: 1.0.0
    managed-by: kubectl
spec:
  selector:
    matchLabels:
      part-of: k8s-anotherclass
      component: backend-server
      name: api-tester
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        part-of: k8s-anotherclass
        component: backend-server
        name: api-tester
        instance: api-tester
        version: 1.0.0
        blue-green-no: "1"
    spec:
      nodeSelector:
        kubernetes.io/hostname: jh-mater
      containers:
        - name: api-tester-1
          image: wogns1063/app-v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
